GET http://localhost:3333/

###

POST http://localhost:3333/cadastrar
Content-Type: application/json

{
    "nome":"Berrnardo", 
    "senha":"888", 
    "email":"mi@hotmal.com"
}



###

PUT http://localhost:3333/atualizar/8
Content-Type: application/json

{

    
    
    "nome":"Paulene", 
    "email":"Paulo@hotmal.com",
    "senha":"7777"
    
}

###

DELETE http://localhost:3333/deletar/8

###

POST http://localhost:3333/login
Content-Type: application/json
{
 

    "senha":"3333", 
    "email":"Mateus@gmail.com"
}

###

GET http://localhost:3333/botas